apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terriamap
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: terriamap
    spec:
      containers:
      - name: terriamap
        resources:
{{ toYaml .Values.resources | indent 10 }}
        command: [ "node", "./node_modules/terriajs-server/lib/app.js", "--config-file", "/etc/config/server/serverconfig.json"]
        env:
        - name: NODE_ENV
          value: production
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        volumeMounts:
          - name: terriamap-config-client
            mountPath: /etc/config/client
          - name: terriamap-config-server
            mountPath: /etc/config/server
      volumes:
        - name: terriamap-config-client
          configMap:
            name: terriamap-config-client
        - name: terriamap-config-server
          configMap:
            name: terriamap-config-server
